/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing E3EAPIDataModelsDataObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class E3EAPIDataModelsDataObjectTests
    {
        // TODO uncomment below to declare an instance variable for E3EAPIDataModelsDataObject
        //private E3EAPIDataModelsDataObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of E3EAPIDataModelsDataObject
            //instance = new E3EAPIDataModelsDataObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of E3EAPIDataModelsDataObject
        /// </summary>
        [Test]
        public void E3EAPIDataModelsDataObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" E3EAPIDataModelsDataObject
            //Assert.IsInstanceOf(typeof(E3EAPIDataModelsDataObject), instance);
        }


        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Test]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }
        /// <summary>
        /// Test the property 'ActualRowCount'
        /// </summary>
        [Test]
        public void ActualRowCountTest()
        {
            // TODO unit test for the property 'ActualRowCount'
        }
        /// <summary>
        /// Test the property 'DataLoadState'
        /// </summary>
        [Test]
        public void DataLoadStateTest()
        {
            // TODO unit test for the property 'DataLoadState'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'GroupCount'
        /// </summary>
        [Test]
        public void GroupCountTest()
        {
            // TODO unit test for the property 'GroupCount'
        }
        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Test]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }
        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Test]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Test]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
        /// <summary>
        /// Test the property 'RowCount'
        /// </summary>
        [Test]
        public void RowCountTest()
        {
            // TODO unit test for the property 'RowCount'
        }
        /// <summary>
        /// Test the property 'Rows'
        /// </summary>
        [Test]
        public void RowsTest()
        {
            // TODO unit test for the property 'Rows'
        }
        /// <summary>
        /// Test the property 'Totals'
        /// </summary>
        [Test]
        public void TotalsTest()
        {
            // TODO unit test for the property 'Totals'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'EditedGroup'
        /// </summary>
        [Test]
        public void EditedGroupTest()
        {
            // TODO unit test for the property 'EditedGroup'
        }

    }

}
