/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing E3EAPIAttachmentModelsAttachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class E3EAPIAttachmentModelsAttachmentTests
    {
        // TODO uncomment below to declare an instance variable for E3EAPIAttachmentModelsAttachment
        //private E3EAPIAttachmentModelsAttachment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of E3EAPIAttachmentModelsAttachment
            //instance = new E3EAPIAttachmentModelsAttachment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of E3EAPIAttachmentModelsAttachment
        /// </summary>
        [Test]
        public void E3EAPIAttachmentModelsAttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" E3EAPIAttachmentModelsAttachment
            //Assert.IsInstanceOf(typeof(E3EAPIAttachmentModelsAttachment), instance);
        }


        /// <summary>
        /// Test the property 'AttachmentID'
        /// </summary>
        [Test]
        public void AttachmentIDTest()
        {
            // TODO unit test for the property 'AttachmentID'
        }
        /// <summary>
        /// Test the property 'AttachmentType'
        /// </summary>
        [Test]
        public void AttachmentTypeTest()
        {
            // TODO unit test for the property 'AttachmentType'
        }
        /// <summary>
        /// Test the property 'DmsDocumentID'
        /// </summary>
        [Test]
        public void DmsDocumentIDTest()
        {
            // TODO unit test for the property 'DmsDocumentID'
        }
        /// <summary>
        /// Test the property 'DmsDraft'
        /// </summary>
        [Test]
        public void DmsDraftTest()
        {
            // TODO unit test for the property 'DmsDraft'
        }
        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Test]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'SyncID'
        /// </summary>
        [Test]
        public void SyncIDTest()
        {
            // TODO unit test for the property 'SyncID'
        }
        /// <summary>
        /// Test the property 'ReportPrint'
        /// </summary>
        [Test]
        public void ReportPrintTest()
        {
            // TODO unit test for the property 'ReportPrint'
        }
        /// <summary>
        /// Test the property 'ExtendedAttributes'
        /// </summary>
        [Test]
        public void ExtendedAttributesTest()
        {
            // TODO unit test for the property 'ExtendedAttributes'
        }
        /// <summary>
        /// Test the property 'SubFolder'
        /// </summary>
        [Test]
        public void SubFolderTest()
        {
            // TODO unit test for the property 'SubFolder'
        }

    }

}
