/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing E3EAPIQuerySJQLSJSelect
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class E3EAPIQuerySJQLSJSelectTests
    {
        // TODO uncomment below to declare an instance variable for E3EAPIQuerySJQLSJSelect
        //private E3EAPIQuerySJQLSJSelect instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of E3EAPIQuerySJQLSJSelect
            //instance = new E3EAPIQuerySJQLSJSelect();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of E3EAPIQuerySJQLSJSelect
        /// </summary>
        [Test]
        public void E3EAPIQuerySJQLSJSelectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" E3EAPIQuerySJQLSJSelect
            //Assert.IsInstanceOf(typeof(E3EAPIQuerySJQLSJSelect), instance);
        }


        /// <summary>
        /// Test the property 'Archetype'
        /// </summary>
        [Test]
        public void ArchetypeTest()
        {
            // TODO unit test for the property 'Archetype'
        }
        /// <summary>
        /// Test the property 'ArchetypeType'
        /// </summary>
        [Test]
        public void ArchetypeTypeTest()
        {
            // TODO unit test for the property 'ArchetypeType'
        }
        /// <summary>
        /// Test the property 'Top'
        /// </summary>
        [Test]
        public void TopTest()
        {
            // TODO unit test for the property 'Top'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Where'
        /// </summary>
        [Test]
        public void WhereTest()
        {
            // TODO unit test for the property 'Where'
        }
        /// <summary>
        /// Test the property 'Joins'
        /// </summary>
        [Test]
        public void JoinsTest()
        {
            // TODO unit test for the property 'Joins'
        }
        /// <summary>
        /// Test the property 'SortBy'
        /// </summary>
        [Test]
        public void SortByTest()
        {
            // TODO unit test for the property 'SortBy'
        }

    }

}
