/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing E3EAPITimeModelsTimecardCleanupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class E3EAPITimeModelsTimecardCleanupRequestTests
    {
        // TODO uncomment below to declare an instance variable for E3EAPITimeModelsTimecardCleanupRequest
        //private E3EAPITimeModelsTimecardCleanupRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of E3EAPITimeModelsTimecardCleanupRequest
            //instance = new E3EAPITimeModelsTimecardCleanupRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of E3EAPITimeModelsTimecardCleanupRequest
        /// </summary>
        [Test]
        public void E3EAPITimeModelsTimecardCleanupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" E3EAPITimeModelsTimecardCleanupRequest
            //Assert.IsInstanceOf(typeof(E3EAPITimeModelsTimecardCleanupRequest), instance);
        }


        /// <summary>
        /// Test the property 'KeepTimecardsWithNarrative'
        /// </summary>
        [Test]
        public void KeepTimecardsWithNarrativeTest()
        {
            // TODO unit test for the property 'KeepTimecardsWithNarrative'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'TimekeeperIndex'
        /// </summary>
        [Test]
        public void TimekeeperIndexTest()
        {
            // TODO unit test for the property 'TimekeeperIndex'
        }
        /// <summary>
        /// Test the property 'TimekeeperNumber'
        /// </summary>
        [Test]
        public void TimekeeperNumberTest()
        {
            // TODO unit test for the property 'TimekeeperNumber'
        }
        /// <summary>
        /// Test the property 'TimekeeperID'
        /// </summary>
        [Test]
        public void TimekeeperIDTest()
        {
            // TODO unit test for the property 'TimekeeperID'
        }
        /// <summary>
        /// Test the property 'ItemIds'
        /// </summary>
        [Test]
        public void ItemIdsTest()
        {
            // TODO unit test for the property 'ItemIds'
        }
        /// <summary>
        /// Test the property 'AttributesToInclude'
        /// </summary>
        [Test]
        public void AttributesToIncludeTest()
        {
            // TODO unit test for the property 'AttributesToInclude'
        }
        /// <summary>
        /// Test the property 'FilterXOQL'
        /// </summary>
        [Test]
        public void FilterXOQLTest()
        {
            // TODO unit test for the property 'FilterXOQL'
        }
        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Test]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

    }

}
