/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing E3EAPITimeModelsTimecard
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class E3EAPITimeModelsTimecardTests
    {
        // TODO uncomment below to declare an instance variable for E3EAPITimeModelsTimecard
        //private E3EAPITimeModelsTimecard instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of E3EAPITimeModelsTimecard
            //instance = new E3EAPITimeModelsTimecard();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of E3EAPITimeModelsTimecard
        /// </summary>
        [Test]
        public void E3EAPITimeModelsTimecardInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" E3EAPITimeModelsTimecard
            //Assert.IsInstanceOf(typeof(E3EAPITimeModelsTimecard), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AccessType'
        /// </summary>
        [Test]
        public void AccessTypeTest()
        {
            // TODO unit test for the property 'AccessType'
        }
        /// <summary>
        /// Test the property 'DataState'
        /// </summary>
        [Test]
        public void DataStateTest()
        {
            // TODO unit test for the property 'DataState'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'ChildObjects'
        /// </summary>
        [Test]
        public void ChildObjectsTest()
        {
            // TODO unit test for the property 'ChildObjects'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Test]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }
        /// <summary>
        /// Test the property 'IsLocked'
        /// </summary>
        [Test]
        public void IsLockedTest()
        {
            // TODO unit test for the property 'IsLocked'
        }
        /// <summary>
        /// Test the property 'LockedMessage'
        /// </summary>
        [Test]
        public void LockedMessageTest()
        {
            // TODO unit test for the property 'LockedMessage'
        }
        /// <summary>
        /// Test the property 'SubclassId'
        /// </summary>
        [Test]
        public void SubclassIdTest()
        {
            // TODO unit test for the property 'SubclassId'
        }

    }

}
