/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing E3EAPITimeModelsCalendarHours
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class E3EAPITimeModelsCalendarHoursTests
    {
        // TODO uncomment below to declare an instance variable for E3EAPITimeModelsCalendarHours
        //private E3EAPITimeModelsCalendarHours instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of E3EAPITimeModelsCalendarHours
            //instance = new E3EAPITimeModelsCalendarHours();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of E3EAPITimeModelsCalendarHours
        /// </summary>
        [Test]
        public void E3EAPITimeModelsCalendarHoursInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" E3EAPITimeModelsCalendarHours
            //Assert.IsInstanceOf(typeof(E3EAPITimeModelsCalendarHours), instance);
        }


        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Sun'
        /// </summary>
        [Test]
        public void SunTest()
        {
            // TODO unit test for the property 'Sun'
        }
        /// <summary>
        /// Test the property 'Mon'
        /// </summary>
        [Test]
        public void MonTest()
        {
            // TODO unit test for the property 'Mon'
        }
        /// <summary>
        /// Test the property 'Tue'
        /// </summary>
        [Test]
        public void TueTest()
        {
            // TODO unit test for the property 'Tue'
        }
        /// <summary>
        /// Test the property 'Wen'
        /// </summary>
        [Test]
        public void WenTest()
        {
            // TODO unit test for the property 'Wen'
        }
        /// <summary>
        /// Test the property 'Thu'
        /// </summary>
        [Test]
        public void ThuTest()
        {
            // TODO unit test for the property 'Thu'
        }
        /// <summary>
        /// Test the property 'Fri'
        /// </summary>
        [Test]
        public void FriTest()
        {
            // TODO unit test for the property 'Fri'
        }
        /// <summary>
        /// Test the property 'Sat'
        /// </summary>
        [Test]
        public void SatTest()
        {
            // TODO unit test for the property 'Sat'
        }

    }

}
