/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing E3EAPIClientModelsClientValidateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class E3EAPIClientModelsClientValidateRequestTests
    {
        // TODO uncomment below to declare an instance variable for E3EAPIClientModelsClientValidateRequest
        //private E3EAPIClientModelsClientValidateRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of E3EAPIClientModelsClientValidateRequest
            //instance = new E3EAPIClientModelsClientValidateRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of E3EAPIClientModelsClientValidateRequest
        /// </summary>
        [Test]
        public void E3EAPIClientModelsClientValidateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" E3EAPIClientModelsClientValidateRequest
            //Assert.IsInstanceOf(typeof(E3EAPIClientModelsClientValidateRequest), instance);
        }


        /// <summary>
        /// Test the property 'ItemId'
        /// </summary>
        [Test]
        public void ItemIdTest()
        {
            // TODO unit test for the property 'ItemId'
        }

    }

}
