/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing E3EAPIDataObjectModelModelsDataObjectModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class E3EAPIDataObjectModelModelsDataObjectModelTests
    {
        // TODO uncomment below to declare an instance variable for E3EAPIDataObjectModelModelsDataObjectModel
        //private E3EAPIDataObjectModelModelsDataObjectModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of E3EAPIDataObjectModelModelsDataObjectModel
            //instance = new E3EAPIDataObjectModelModelsDataObjectModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of E3EAPIDataObjectModelModelsDataObjectModel
        /// </summary>
        [Test]
        public void E3EAPIDataObjectModelModelsDataObjectModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" E3EAPIDataObjectModelModelsDataObjectModel
            //Assert.IsInstanceOf(typeof(E3EAPIDataObjectModelModelsDataObjectModel), instance);
        }


        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ModelId'
        /// </summary>
        [Test]
        public void ModelIdTest()
        {
            // TODO unit test for the property 'ModelId'
        }
        /// <summary>
        /// Test the property 'IsGlobal'
        /// </summary>
        [Test]
        public void IsGlobalTest()
        {
            // TODO unit test for the property 'IsGlobal'
        }
        /// <summary>
        /// Test the property 'CanEdit'
        /// </summary>
        [Test]
        public void CanEditTest()
        {
            // TODO unit test for the property 'CanEdit'
        }

    }

}
