/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing E3EAPIQuerySJQLSJPredicate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class E3EAPIQuerySJQLSJPredicateTests
    {
        // TODO uncomment below to declare an instance variable for E3EAPIQuerySJQLSJPredicate
        //private E3EAPIQuerySJQLSJPredicate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of E3EAPIQuerySJQLSJPredicate
            //instance = new E3EAPIQuerySJQLSJPredicate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of E3EAPIQuerySJQLSJPredicate
        /// </summary>
        [Test]
        public void E3EAPIQuerySJQLSJPredicateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" E3EAPIQuerySJQLSJPredicate
            //Assert.IsInstanceOf(typeof(E3EAPIQuerySJQLSJPredicate), instance);
        }


        /// <summary>
        /// Test the property 'Attribute'
        /// </summary>
        [Test]
        public void AttributeTest()
        {
            // TODO unit test for the property 'Attribute'
        }
        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Test]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }
        /// <summary>
        /// Test the property 'OperatorUnit'
        /// </summary>
        [Test]
        public void OperatorUnitTest()
        {
            // TODO unit test for the property 'OperatorUnit'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Select'
        /// </summary>
        [Test]
        public void SelectTest()
        {
            // TODO unit test for the property 'Select'
        }

    }

}
