/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing NextGenFrameworkManagersObjectMgrQueryIDraftQuery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NextGenFrameworkManagersObjectMgrQueryIDraftQueryTests
    {
        // TODO uncomment below to declare an instance variable for NextGenFrameworkManagersObjectMgrQueryIDraftQuery
        //private NextGenFrameworkManagersObjectMgrQueryIDraftQuery instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NextGenFrameworkManagersObjectMgrQueryIDraftQuery
            //instance = new NextGenFrameworkManagersObjectMgrQueryIDraftQuery();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NextGenFrameworkManagersObjectMgrQueryIDraftQuery
        /// </summary>
        [Test]
        public void NextGenFrameworkManagersObjectMgrQueryIDraftQueryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" NextGenFrameworkManagersObjectMgrQueryIDraftQuery
            //Assert.IsInstanceOf(typeof(NextGenFrameworkManagersObjectMgrQueryIDraftQuery), instance);
        }


        /// <summary>
        /// Test the property 'DraftID'
        /// </summary>
        [Test]
        public void DraftIDTest()
        {
            // TODO unit test for the property 'DraftID'
        }
        /// <summary>
        /// Test the property 'DraftVersion'
        /// </summary>
        [Test]
        public void DraftVersionTest()
        {
            // TODO unit test for the property 'DraftVersion'
        }
        /// <summary>
        /// Test the property 'DraftState'
        /// </summary>
        [Test]
        public void DraftStateTest()
        {
            // TODO unit test for the property 'DraftState'
        }
        /// <summary>
        /// Test the property 'DraftAccess'
        /// </summary>
        [Test]
        public void DraftAccessTest()
        {
            // TODO unit test for the property 'DraftAccess'
        }
        /// <summary>
        /// Test the property 'DraftExceptions'
        /// </summary>
        [Test]
        public void DraftExceptionsTest()
        {
            // TODO unit test for the property 'DraftExceptions'
        }
        /// <summary>
        /// Test the property 'DraftMessages'
        /// </summary>
        [Test]
        public void DraftMessagesTest()
        {
            // TODO unit test for the property 'DraftMessages'
        }
        /// <summary>
        /// Test the property 'DraftAudit'
        /// </summary>
        [Test]
        public void DraftAuditTest()
        {
            // TODO unit test for the property 'DraftAudit'
        }

    }

}
