/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing NextGenFrameworkManagersObjectMgrSchemaIAttribute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NextGenFrameworkManagersObjectMgrSchemaIAttributeTests
    {
        // TODO uncomment below to declare an instance variable for NextGenFrameworkManagersObjectMgrSchemaIAttribute
        //private NextGenFrameworkManagersObjectMgrSchemaIAttribute instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NextGenFrameworkManagersObjectMgrSchemaIAttribute
            //instance = new NextGenFrameworkManagersObjectMgrSchemaIAttribute();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NextGenFrameworkManagersObjectMgrSchemaIAttribute
        /// </summary>
        [Test]
        public void NextGenFrameworkManagersObjectMgrSchemaIAttributeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" NextGenFrameworkManagersObjectMgrSchemaIAttribute
            //Assert.IsInstanceOf(typeof(NextGenFrameworkManagersObjectMgrSchemaIAttribute), instance);
        }


        /// <summary>
        /// Test the property 'DefaultValue'
        /// </summary>
        [Test]
        public void DefaultValueTest()
        {
            // TODO unit test for the property 'DefaultValue'
        }
        /// <summary>
        /// Test the property 'DraftOrdinal'
        /// </summary>
        [Test]
        public void DraftOrdinalTest()
        {
            // TODO unit test for the property 'DraftOrdinal'
        }
        /// <summary>
        /// Test the property 'TemplateOrdinal'
        /// </summary>
        [Test]
        public void TemplateOrdinalTest()
        {
            // TODO unit test for the property 'TemplateOrdinal'
        }
        /// <summary>
        /// Test the property 'LinkedAttributes'
        /// </summary>
        [Test]
        public void LinkedAttributesTest()
        {
            // TODO unit test for the property 'LinkedAttributes'
        }

    }

}
