/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing NextGenFrameworkManagersDMSMgrIDMSFolder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NextGenFrameworkManagersDMSMgrIDMSFolderTests
    {
        // TODO uncomment below to declare an instance variable for NextGenFrameworkManagersDMSMgrIDMSFolder
        //private NextGenFrameworkManagersDMSMgrIDMSFolder instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NextGenFrameworkManagersDMSMgrIDMSFolder
            //instance = new NextGenFrameworkManagersDMSMgrIDMSFolder();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NextGenFrameworkManagersDMSMgrIDMSFolder
        /// </summary>
        [Test]
        public void NextGenFrameworkManagersDMSMgrIDMSFolderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" NextGenFrameworkManagersDMSMgrIDMSFolder
            //Assert.IsInstanceOf(typeof(NextGenFrameworkManagersDMSMgrIDMSFolder), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'IsHidden'
        /// </summary>
        [Test]
        public void IsHiddenTest()
        {
            // TODO unit test for the property 'IsHidden'
        }
        /// <summary>
        /// Test the property 'DocCount'
        /// </summary>
        [Test]
        public void DocCountTest()
        {
            // TODO unit test for the property 'DocCount'
        }
        /// <summary>
        /// Test the property 'SubFolders'
        /// </summary>
        [Test]
        public void SubFoldersTest()
        {
            // TODO unit test for the property 'SubFolders'
        }

    }

}
