/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The standard request to delete a data object model.
    /// </summary>
    [DataContract]
    public partial class E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest :  IEquatable<E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest" /> class.
        /// </summary>
        /// <param name="modelId">Gets or sets the ID of a model that is going to be deleted. (required).</param>
        public E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest(Guid modelId = default(Guid))
        {
            // to ensure "modelId" is required (not null)
            if (modelId == null)
            {
                throw new InvalidDataException("modelId is a required property for E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest and cannot be null");
            }
            else
            {
                this.ModelId = modelId;
            }

        }

        /// <summary>
        /// Gets or sets the ID of a model that is going to be deleted.
        /// </summary>
        /// <value>Gets or sets the ID of a model that is going to be deleted.</value>
        [DataMember(Name="modelId", EmitDefaultValue=true)]
        public Guid ModelId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest {\n");
            sb.Append("  ModelId: ").Append(ModelId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest);
        }

        /// <summary>
        /// Returns true if E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(E3EAPIDataObjectModelModelsDataObjectModelDeleteRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ModelId == input.ModelId ||
                    (this.ModelId != null &&
                    this.ModelId.Equals(input.ModelId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ModelId != null)
                    hashCode = hashCode * 59 + this.ModelId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
