/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Response to TimecardAllResponse.
    /// </summary>
    [DataContract]
    public partial class E3EAPITimeModelsTimecardGetAllResponse :  IEquatable<E3EAPITimeModelsTimecardGetAllResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="E3EAPITimeModelsTimecardGetAllResponse" /> class.
        /// </summary>
        /// <param name="timecardPendingObjects">Gets or sets the pending timecards..</param>
        /// <param name="timecardPostedObjects">Gets or sets the posted timecards..</param>
        /// <param name="success">success.</param>
        /// <param name="message">message.</param>
        public E3EAPITimeModelsTimecardGetAllResponse(List<E3EAPITimeModelsTimecard> timecardPendingObjects = default(List<E3EAPITimeModelsTimecard>), List<E3EAPITimeModelsTimecard> timecardPostedObjects = default(List<E3EAPITimeModelsTimecard>), bool success = default(bool), string message = default(string))
        {
            this.TimecardPendingObjects = timecardPendingObjects;
            this.TimecardPostedObjects = timecardPostedObjects;
            this.Message = message;
            this.TimecardPendingObjects = timecardPendingObjects;
            this.TimecardPostedObjects = timecardPostedObjects;
            this.Success = success;
            this.Message = message;
        }

        /// <summary>
        /// Gets or sets the pending timecards.
        /// </summary>
        /// <value>Gets or sets the pending timecards.</value>
        [DataMember(Name="timecardPendingObjects", EmitDefaultValue=true)]
        public List<E3EAPITimeModelsTimecard> TimecardPendingObjects { get; set; }

        /// <summary>
        /// Gets or sets the posted timecards.
        /// </summary>
        /// <value>Gets or sets the posted timecards.</value>
        [DataMember(Name="timecardPostedObjects", EmitDefaultValue=true)]
        public List<E3EAPITimeModelsTimecard> TimecardPostedObjects { get; set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name="success", EmitDefaultValue=false)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=true)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class E3EAPITimeModelsTimecardGetAllResponse {\n");
            sb.Append("  TimecardPendingObjects: ").Append(TimecardPendingObjects).Append("\n");
            sb.Append("  TimecardPostedObjects: ").Append(TimecardPostedObjects).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as E3EAPITimeModelsTimecardGetAllResponse);
        }

        /// <summary>
        /// Returns true if E3EAPITimeModelsTimecardGetAllResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of E3EAPITimeModelsTimecardGetAllResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(E3EAPITimeModelsTimecardGetAllResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TimecardPendingObjects == input.TimecardPendingObjects ||
                    this.TimecardPendingObjects != null &&
                    input.TimecardPendingObjects != null &&
                    this.TimecardPendingObjects.SequenceEqual(input.TimecardPendingObjects)
                ) && 
                (
                    this.TimecardPostedObjects == input.TimecardPostedObjects ||
                    this.TimecardPostedObjects != null &&
                    input.TimecardPostedObjects != null &&
                    this.TimecardPostedObjects.SequenceEqual(input.TimecardPostedObjects)
                ) && 
                (
                    this.Success == input.Success ||
                    (this.Success != null &&
                    this.Success.Equals(input.Success))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TimecardPendingObjects != null)
                    hashCode = hashCode * 59 + this.TimecardPendingObjects.GetHashCode();
                if (this.TimecardPostedObjects != null)
                    hashCode = hashCode * 59 + this.TimecardPostedObjects.GetHashCode();
                if (this.Success != null)
                    hashCode = hashCode * 59 + this.Success.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
