/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Contains parameters to make a request to start a timer.
    /// </summary>
    [DataContract]
    public partial class E3EAPITimeModelsStartStopTimerRequest :  IEquatable<E3EAPITimeModelsStartStopTimerRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="E3EAPITimeModelsStartStopTimerRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected E3EAPITimeModelsStartStopTimerRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="E3EAPITimeModelsStartStopTimerRequest" /> class.
        /// </summary>
        /// <param name="today">Gets or sets the client&#39;s current date/time. (required).</param>
        /// <param name="timecardIndex">Gets or sets the timecard index. (required).</param>
        public E3EAPITimeModelsStartStopTimerRequest(DateTime today = default(DateTime), string timecardIndex = default(string))
        {
            // to ensure "today" is required (not null)
            if (today == null)
            {
                throw new InvalidDataException("today is a required property for E3EAPITimeModelsStartStopTimerRequest and cannot be null");
            }
            else
            {
                this.Today = today;
            }

            // to ensure "timecardIndex" is required (not null)
            if (timecardIndex == null)
            {
                throw new InvalidDataException("timecardIndex is a required property for E3EAPITimeModelsStartStopTimerRequest and cannot be null");
            }
            else
            {
                this.TimecardIndex = timecardIndex;
            }

        }

        /// <summary>
        /// Gets or sets the client&#39;s current date/time.
        /// </summary>
        /// <value>Gets or sets the client&#39;s current date/time.</value>
        [DataMember(Name="today", EmitDefaultValue=true)]
        public DateTime Today { get; set; }

        /// <summary>
        /// Gets or sets the timecard index.
        /// </summary>
        /// <value>Gets or sets the timecard index.</value>
        [DataMember(Name="timecardIndex", EmitDefaultValue=true)]
        public string TimecardIndex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class E3EAPITimeModelsStartStopTimerRequest {\n");
            sb.Append("  Today: ").Append(Today).Append("\n");
            sb.Append("  TimecardIndex: ").Append(TimecardIndex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as E3EAPITimeModelsStartStopTimerRequest);
        }

        /// <summary>
        /// Returns true if E3EAPITimeModelsStartStopTimerRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of E3EAPITimeModelsStartStopTimerRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(E3EAPITimeModelsStartStopTimerRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Today == input.Today ||
                    (this.Today != null &&
                    this.Today.Equals(input.Today))
                ) && 
                (
                    this.TimecardIndex == input.TimecardIndex ||
                    (this.TimecardIndex != null &&
                    this.TimecardIndex.Equals(input.TimecardIndex))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Today != null)
                    hashCode = hashCode * 59 + this.Today.GetHashCode();
                if (this.TimecardIndex != null)
                    hashCode = hashCode * 59 + this.TimecardIndex.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
