/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Response to a get request.
    /// </summary>
    [DataContract]
    public partial class E3EAPIEntityModelsEntityGetResponse :  IEquatable<E3EAPIEntityModelsEntityGetResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="E3EAPIEntityModelsEntityGetResponse" /> class.
        /// </summary>
        /// <param name="persons">Gets or sets a collection of EntityPerson objects..</param>
        /// <param name="organizations">Gets or sets a collection of EntityOrg objects..</param>
        /// <param name="success">success.</param>
        /// <param name="message">message.</param>
        public E3EAPIEntityModelsEntityGetResponse(List<E3EAPIEntityModelsEntity> persons = default(List<E3EAPIEntityModelsEntity>), List<E3EAPIEntityModelsEntity> organizations = default(List<E3EAPIEntityModelsEntity>), bool success = default(bool), string message = default(string))
        {
            this.Persons = persons;
            this.Organizations = organizations;
            this.Message = message;
            this.Persons = persons;
            this.Organizations = organizations;
            this.Success = success;
            this.Message = message;
        }

        /// <summary>
        /// Gets or sets a collection of EntityPerson objects.
        /// </summary>
        /// <value>Gets or sets a collection of EntityPerson objects.</value>
        [DataMember(Name="persons", EmitDefaultValue=true)]
        public List<E3EAPIEntityModelsEntity> Persons { get; set; }

        /// <summary>
        /// Gets or sets a collection of EntityOrg objects.
        /// </summary>
        /// <value>Gets or sets a collection of EntityOrg objects.</value>
        [DataMember(Name="organizations", EmitDefaultValue=true)]
        public List<E3EAPIEntityModelsEntity> Organizations { get; set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name="success", EmitDefaultValue=false)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=true)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class E3EAPIEntityModelsEntityGetResponse {\n");
            sb.Append("  Persons: ").Append(Persons).Append("\n");
            sb.Append("  Organizations: ").Append(Organizations).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as E3EAPIEntityModelsEntityGetResponse);
        }

        /// <summary>
        /// Returns true if E3EAPIEntityModelsEntityGetResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of E3EAPIEntityModelsEntityGetResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(E3EAPIEntityModelsEntityGetResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Persons == input.Persons ||
                    this.Persons != null &&
                    input.Persons != null &&
                    this.Persons.SequenceEqual(input.Persons)
                ) && 
                (
                    this.Organizations == input.Organizations ||
                    this.Organizations != null &&
                    input.Organizations != null &&
                    this.Organizations.SequenceEqual(input.Organizations)
                ) && 
                (
                    this.Success == input.Success ||
                    (this.Success != null &&
                    this.Success.Equals(input.Success))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Persons != null)
                    hashCode = hashCode * 59 + this.Persons.GetHashCode();
                if (this.Organizations != null)
                    hashCode = hashCode * 59 + this.Organizations.GetHashCode();
                if (this.Success != null)
                    hashCode = hashCode * 59 + this.Success.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
