/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents the types of appobjects that can be run from a dashboard.
    /// </summary>
    /// <value>Represents the types of appobjects that can be run from a dashboard.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum E3EAPIAppObjectType
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        NUMBER_0 = 1,

        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        [EnumMember(Value = "1")]
        NUMBER_1 = 2,

        /// <summary>
        /// Enum NUMBER_2 for value: 2
        /// </summary>
        [EnumMember(Value = "2")]
        NUMBER_2 = 3,

        /// <summary>
        /// Enum NUMBER_4 for value: 4
        /// </summary>
        [EnumMember(Value = "4")]
        NUMBER_4 = 4,

        /// <summary>
        /// Enum NUMBER_5 for value: 5
        /// </summary>
        [EnumMember(Value = "5")]
        NUMBER_5 = 5,

        /// <summary>
        /// Enum NUMBER_6 for value: 6
        /// </summary>
        [EnumMember(Value = "6")]
        NUMBER_6 = 6,

        /// <summary>
        /// Enum NUMBER_7 for value: 7
        /// </summary>
        [EnumMember(Value = "7")]
        NUMBER_7 = 7,

        /// <summary>
        /// Enum NUMBER_9 for value: 9
        /// </summary>
        [EnumMember(Value = "9")]
        NUMBER_9 = 8,

        /// <summary>
        /// Enum NUMBER_11 for value: 11
        /// </summary>
        [EnumMember(Value = "11")]
        NUMBER_11 = 9,

        /// <summary>
        /// Enum NUMBER_13 for value: 13
        /// </summary>
        [EnumMember(Value = "13")]
        NUMBER_13 = 10,

        /// <summary>
        /// Enum NUMBER_14 for value: 14
        /// </summary>
        [EnumMember(Value = "14")]
        NUMBER_14 = 11,

        /// <summary>
        /// Enum NUMBER_16 for value: 16
        /// </summary>
        [EnumMember(Value = "16")]
        NUMBER_16 = 12,

        /// <summary>
        /// Enum NUMBER_20 for value: 20
        /// </summary>
        [EnumMember(Value = "20")]
        NUMBER_20 = 13,

        /// <summary>
        /// Enum NUMBER_23 for value: 23
        /// </summary>
        [EnumMember(Value = "23")]
        NUMBER_23 = 14,

        /// <summary>
        /// Enum NUMBER_27 for value: 27
        /// </summary>
        [EnumMember(Value = "27")]
        NUMBER_27 = 15,

        /// <summary>
        /// Enum NUMBER_29 for value: 29
        /// </summary>
        [EnumMember(Value = "29")]
        NUMBER_29 = 16,

        /// <summary>
        /// Enum NUMBER_30 for value: 30
        /// </summary>
        [EnumMember(Value = "30")]
        NUMBER_30 = 17,

        /// <summary>
        /// Enum NUMBER_37 for value: 37
        /// </summary>
        [EnumMember(Value = "37")]
        NUMBER_37 = 18,

        /// <summary>
        /// Enum NUMBER_40 for value: 40
        /// </summary>
        [EnumMember(Value = "40")]
        NUMBER_40 = 19

    }

}
