/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents calendar report response.
    /// </summary>
    [DataContract]
    public partial class E3EAPITimeModelsCalendarReportGetResponse :  IEquatable<E3EAPITimeModelsCalendarReportGetResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="E3EAPITimeModelsCalendarReportGetResponse" /> class.
        /// </summary>
        /// <param name="days">Gets or sets the time submitted per day..</param>
        /// <param name="hours">Gets or sets the Timekeeper calendar..</param>
        /// <param name="success">success.</param>
        /// <param name="message">message.</param>
        public E3EAPITimeModelsCalendarReportGetResponse(List<E3EAPITimeModelsCalendarItem> days = default(List<E3EAPITimeModelsCalendarItem>), List<E3EAPITimeModelsCalendarHours> hours = default(List<E3EAPITimeModelsCalendarHours>), bool success = default(bool), string message = default(string))
        {
            this.Days = days;
            this.Hours = hours;
            this.Message = message;
            this.Days = days;
            this.Hours = hours;
            this.Success = success;
            this.Message = message;
        }

        /// <summary>
        /// Gets or sets the time submitted per day.
        /// </summary>
        /// <value>Gets or sets the time submitted per day.</value>
        [DataMember(Name="days", EmitDefaultValue=true)]
        public List<E3EAPITimeModelsCalendarItem> Days { get; set; }

        /// <summary>
        /// Gets or sets the Timekeeper calendar.
        /// </summary>
        /// <value>Gets or sets the Timekeeper calendar.</value>
        [DataMember(Name="hours", EmitDefaultValue=true)]
        public List<E3EAPITimeModelsCalendarHours> Hours { get; set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name="success", EmitDefaultValue=false)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=true)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class E3EAPITimeModelsCalendarReportGetResponse {\n");
            sb.Append("  Days: ").Append(Days).Append("\n");
            sb.Append("  Hours: ").Append(Hours).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as E3EAPITimeModelsCalendarReportGetResponse);
        }

        /// <summary>
        /// Returns true if E3EAPITimeModelsCalendarReportGetResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of E3EAPITimeModelsCalendarReportGetResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(E3EAPITimeModelsCalendarReportGetResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Days == input.Days ||
                    this.Days != null &&
                    input.Days != null &&
                    this.Days.SequenceEqual(input.Days)
                ) && 
                (
                    this.Hours == input.Hours ||
                    this.Hours != null &&
                    input.Hours != null &&
                    this.Hours.SequenceEqual(input.Hours)
                ) && 
                (
                    this.Success == input.Success ||
                    (this.Success != null &&
                    this.Success.Equals(input.Success))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Days != null)
                    hashCode = hashCode * 59 + this.Days.GetHashCode();
                if (this.Hours != null)
                    hashCode = hashCode * 59 + this.Hours.GetHashCode();
                if (this.Success != null)
                    hashCode = hashCode * 59 + this.Success.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
