/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines NextGen.Framework.Managers.DMSMgr.imObjectType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum NextGenFrameworkManagersDMSMgrImObjectType
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        NUMBER_0 = 1,

        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        [EnumMember(Value = "1")]
        NUMBER_1 = 2,

        /// <summary>
        /// Enum NUMBER_2 for value: 2
        /// </summary>
        [EnumMember(Value = "2")]
        NUMBER_2 = 3,

        /// <summary>
        /// Enum NUMBER_3 for value: 3
        /// </summary>
        [EnumMember(Value = "3")]
        NUMBER_3 = 4,

        /// <summary>
        /// Enum NUMBER_4 for value: 4
        /// </summary>
        [EnumMember(Value = "4")]
        NUMBER_4 = 5,

        /// <summary>
        /// Enum NUMBER_5 for value: 5
        /// </summary>
        [EnumMember(Value = "5")]
        NUMBER_5 = 6,

        /// <summary>
        /// Enum NUMBER_6 for value: 6
        /// </summary>
        [EnumMember(Value = "6")]
        NUMBER_6 = 7,

        /// <summary>
        /// Enum NUMBER_7 for value: 7
        /// </summary>
        [EnumMember(Value = "7")]
        NUMBER_7 = 8,

        /// <summary>
        /// Enum NUMBER_8 for value: 8
        /// </summary>
        [EnumMember(Value = "8")]
        NUMBER_8 = 9,

        /// <summary>
        /// Enum NUMBER_9 for value: 9
        /// </summary>
        [EnumMember(Value = "9")]
        NUMBER_9 = 10,

        /// <summary>
        /// Enum NUMBER_10 for value: 10
        /// </summary>
        [EnumMember(Value = "10")]
        NUMBER_10 = 11,

        /// <summary>
        /// Enum NUMBER_11 for value: 11
        /// </summary>
        [EnumMember(Value = "11")]
        NUMBER_11 = 12,

        /// <summary>
        /// Enum NUMBER_12 for value: 12
        /// </summary>
        [EnumMember(Value = "12")]
        NUMBER_12 = 13,

        /// <summary>
        /// Enum NUMBER_13 for value: 13
        /// </summary>
        [EnumMember(Value = "13")]
        NUMBER_13 = 14,

        /// <summary>
        /// Enum NUMBER_14 for value: 14
        /// </summary>
        [EnumMember(Value = "14")]
        NUMBER_14 = 15,

        /// <summary>
        /// Enum NUMBER_15 for value: 15
        /// </summary>
        [EnumMember(Value = "15")]
        NUMBER_15 = 16,

        /// <summary>
        /// Enum NUMBER_16 for value: 16
        /// </summary>
        [EnumMember(Value = "16")]
        NUMBER_16 = 17,

        /// <summary>
        /// Enum NUMBER_17 for value: 17
        /// </summary>
        [EnumMember(Value = "17")]
        NUMBER_17 = 18,

        /// <summary>
        /// Enum NUMBER_18 for value: 18
        /// </summary>
        [EnumMember(Value = "18")]
        NUMBER_18 = 19,

        /// <summary>
        /// Enum NUMBER_19 for value: 19
        /// </summary>
        [EnumMember(Value = "19")]
        NUMBER_19 = 20,

        /// <summary>
        /// Enum NUMBER_20 for value: 20
        /// </summary>
        [EnumMember(Value = "20")]
        NUMBER_20 = 21,

        /// <summary>
        /// Enum NUMBER_21 for value: 21
        /// </summary>
        [EnumMember(Value = "21")]
        NUMBER_21 = 22,

        /// <summary>
        /// Enum NUMBER_22 for value: 22
        /// </summary>
        [EnumMember(Value = "22")]
        NUMBER_22 = 23,

        /// <summary>
        /// Enum NUMBER_23 for value: 23
        /// </summary>
        [EnumMember(Value = "23")]
        NUMBER_23 = 24,

        /// <summary>
        /// Enum NUMBER_24 for value: 24
        /// </summary>
        [EnumMember(Value = "24")]
        NUMBER_24 = 25,

        /// <summary>
        /// Enum NUMBER_25 for value: 25
        /// </summary>
        [EnumMember(Value = "25")]
        NUMBER_25 = 26,

        /// <summary>
        /// Enum NUMBER_26 for value: 26
        /// </summary>
        [EnumMember(Value = "26")]
        NUMBER_26 = 27,

        /// <summary>
        /// Enum NUMBER_27 for value: 27
        /// </summary>
        [EnumMember(Value = "27")]
        NUMBER_27 = 28,

        /// <summary>
        /// Enum NUMBER_28 for value: 28
        /// </summary>
        [EnumMember(Value = "28")]
        NUMBER_28 = 29,

        /// <summary>
        /// Enum NUMBER_29 for value: 29
        /// </summary>
        [EnumMember(Value = "29")]
        NUMBER_29 = 30,

        /// <summary>
        /// Enum NUMBER_30 for value: 30
        /// </summary>
        [EnumMember(Value = "30")]
        NUMBER_30 = 31,

        /// <summary>
        /// Enum NUMBER_31 for value: 31
        /// </summary>
        [EnumMember(Value = "31")]
        NUMBER_31 = 32,

        /// <summary>
        /// Enum NUMBER_32 for value: 32
        /// </summary>
        [EnumMember(Value = "32")]
        NUMBER_32 = 33,

        /// <summary>
        /// Enum NUMBER_33 for value: 33
        /// </summary>
        [EnumMember(Value = "33")]
        NUMBER_33 = 34,

        /// <summary>
        /// Enum NUMBER_34 for value: 34
        /// </summary>
        [EnumMember(Value = "34")]
        NUMBER_34 = 35,

        /// <summary>
        /// Enum NUMBER_35 for value: 35
        /// </summary>
        [EnumMember(Value = "35")]
        NUMBER_35 = 36,

        /// <summary>
        /// Enum NUMBER_36 for value: 36
        /// </summary>
        [EnumMember(Value = "36")]
        NUMBER_36 = 37,

        /// <summary>
        /// Enum NUMBER_37 for value: 37
        /// </summary>
        [EnumMember(Value = "37")]
        NUMBER_37 = 38,

        /// <summary>
        /// Enum NUMBER_38 for value: 38
        /// </summary>
        [EnumMember(Value = "38")]
        NUMBER_38 = 39,

        /// <summary>
        /// Enum NUMBER_39 for value: 39
        /// </summary>
        [EnumMember(Value = "39")]
        NUMBER_39 = 40,

        /// <summary>
        /// Enum NUMBER_40 for value: 40
        /// </summary>
        [EnumMember(Value = "40")]
        NUMBER_40 = 41,

        /// <summary>
        /// Enum NUMBER_41 for value: 41
        /// </summary>
        [EnumMember(Value = "41")]
        NUMBER_41 = 42,

        /// <summary>
        /// Enum NUMBER_42 for value: 42
        /// </summary>
        [EnumMember(Value = "42")]
        NUMBER_42 = 43,

        /// <summary>
        /// Enum NUMBER_43 for value: 43
        /// </summary>
        [EnumMember(Value = "43")]
        NUMBER_43 = 44,

        /// <summary>
        /// Enum NUMBER_44 for value: 44
        /// </summary>
        [EnumMember(Value = "44")]
        NUMBER_44 = 45,

        /// <summary>
        /// Enum NUMBER_45 for value: 45
        /// </summary>
        [EnumMember(Value = "45")]
        NUMBER_45 = 46,

        /// <summary>
        /// Enum NUMBER_46 for value: 46
        /// </summary>
        [EnumMember(Value = "46")]
        NUMBER_46 = 47,

        /// <summary>
        /// Enum NUMBER_47 for value: 47
        /// </summary>
        [EnumMember(Value = "47")]
        NUMBER_47 = 48,

        /// <summary>
        /// Enum NUMBER_48 for value: 48
        /// </summary>
        [EnumMember(Value = "48")]
        NUMBER_48 = 49,

        /// <summary>
        /// Enum NUMBER_49 for value: 49
        /// </summary>
        [EnumMember(Value = "49")]
        NUMBER_49 = 50,

        /// <summary>
        /// Enum NUMBER_50 for value: 50
        /// </summary>
        [EnumMember(Value = "50")]
        NUMBER_50 = 51,

        /// <summary>
        /// Enum NUMBER_51 for value: 51
        /// </summary>
        [EnumMember(Value = "51")]
        NUMBER_51 = 52,

        /// <summary>
        /// Enum NUMBER_52 for value: 52
        /// </summary>
        [EnumMember(Value = "52")]
        NUMBER_52 = 53,

        /// <summary>
        /// Enum NUMBER_53 for value: 53
        /// </summary>
        [EnumMember(Value = "53")]
        NUMBER_53 = 54,

        /// <summary>
        /// Enum NUMBER_54 for value: 54
        /// </summary>
        [EnumMember(Value = "54")]
        NUMBER_54 = 55,

        /// <summary>
        /// Enum NUMBER_55 for value: 55
        /// </summary>
        [EnumMember(Value = "55")]
        NUMBER_55 = 56,

        /// <summary>
        /// Enum NUMBER_56 for value: 56
        /// </summary>
        [EnumMember(Value = "56")]
        NUMBER_56 = 57,

        /// <summary>
        /// Enum NUMBER_57 for value: 57
        /// </summary>
        [EnumMember(Value = "57")]
        NUMBER_57 = 58,

        /// <summary>
        /// Enum NUMBER_58 for value: 58
        /// </summary>
        [EnumMember(Value = "58")]
        NUMBER_58 = 59,

        /// <summary>
        /// Enum NUMBER_59 for value: 59
        /// </summary>
        [EnumMember(Value = "59")]
        NUMBER_59 = 60,

        /// <summary>
        /// Enum NUMBER_60 for value: 60
        /// </summary>
        [EnumMember(Value = "60")]
        NUMBER_60 = 61,

        /// <summary>
        /// Enum NUMBER_61 for value: 61
        /// </summary>
        [EnumMember(Value = "61")]
        NUMBER_61 = 62,

        /// <summary>
        /// Enum NUMBER_62 for value: 62
        /// </summary>
        [EnumMember(Value = "62")]
        NUMBER_62 = 63,

        /// <summary>
        /// Enum NUMBER_63 for value: 63
        /// </summary>
        [EnumMember(Value = "63")]
        NUMBER_63 = 64,

        /// <summary>
        /// Enum NUMBER_64 for value: 64
        /// </summary>
        [EnumMember(Value = "64")]
        NUMBER_64 = 65,

        /// <summary>
        /// Enum NUMBER_65 for value: 65
        /// </summary>
        [EnumMember(Value = "65")]
        NUMBER_65 = 66,

        /// <summary>
        /// Enum NUMBER_66 for value: 66
        /// </summary>
        [EnumMember(Value = "66")]
        NUMBER_66 = 67,

        /// <summary>
        /// Enum NUMBER_67 for value: 67
        /// </summary>
        [EnumMember(Value = "67")]
        NUMBER_67 = 68,

        /// <summary>
        /// Enum NUMBER_68 for value: 68
        /// </summary>
        [EnumMember(Value = "68")]
        NUMBER_68 = 69,

        /// <summary>
        /// Enum NUMBER_69 for value: 69
        /// </summary>
        [EnumMember(Value = "69")]
        NUMBER_69 = 70,

        /// <summary>
        /// Enum NUMBER_70 for value: 70
        /// </summary>
        [EnumMember(Value = "70")]
        NUMBER_70 = 71,

        /// <summary>
        /// Enum NUMBER_71 for value: 71
        /// </summary>
        [EnumMember(Value = "71")]
        NUMBER_71 = 72,

        /// <summary>
        /// Enum NUMBER_72 for value: 72
        /// </summary>
        [EnumMember(Value = "72")]
        NUMBER_72 = 73,

        /// <summary>
        /// Enum NUMBER_73 for value: 73
        /// </summary>
        [EnumMember(Value = "73")]
        NUMBER_73 = 74,

        /// <summary>
        /// Enum NUMBER_74 for value: 74
        /// </summary>
        [EnumMember(Value = "74")]
        NUMBER_74 = 75,

        /// <summary>
        /// Enum NUMBER_75 for value: 75
        /// </summary>
        [EnumMember(Value = "75")]
        NUMBER_75 = 76,

        /// <summary>
        /// Enum NUMBER_76 for value: 76
        /// </summary>
        [EnumMember(Value = "76")]
        NUMBER_76 = 77,

        /// <summary>
        /// Enum NUMBER_77 for value: 77
        /// </summary>
        [EnumMember(Value = "77")]
        NUMBER_77 = 78,

        /// <summary>
        /// Enum NUMBER_78 for value: 78
        /// </summary>
        [EnumMember(Value = "78")]
        NUMBER_78 = 79,

        /// <summary>
        /// Enum NUMBER_79 for value: 79
        /// </summary>
        [EnumMember(Value = "79")]
        NUMBER_79 = 80,

        /// <summary>
        /// Enum NUMBER_80 for value: 80
        /// </summary>
        [EnumMember(Value = "80")]
        NUMBER_80 = 81,

        /// <summary>
        /// Enum NUMBER_81 for value: 81
        /// </summary>
        [EnumMember(Value = "81")]
        NUMBER_81 = 82,

        /// <summary>
        /// Enum NUMBER_82 for value: 82
        /// </summary>
        [EnumMember(Value = "82")]
        NUMBER_82 = 83,

        /// <summary>
        /// Enum NUMBER_83 for value: 83
        /// </summary>
        [EnumMember(Value = "83")]
        NUMBER_83 = 84,

        /// <summary>
        /// Enum NUMBER_84 for value: 84
        /// </summary>
        [EnumMember(Value = "84")]
        NUMBER_84 = 85,

        /// <summary>
        /// Enum NUMBER_85 for value: 85
        /// </summary>
        [EnumMember(Value = "85")]
        NUMBER_85 = 86,

        /// <summary>
        /// Enum NUMBER_86 for value: 86
        /// </summary>
        [EnumMember(Value = "86")]
        NUMBER_86 = 87,

        /// <summary>
        /// Enum NUMBER_87 for value: 87
        /// </summary>
        [EnumMember(Value = "87")]
        NUMBER_87 = 88,

        /// <summary>
        /// Enum NUMBER_88 for value: 88
        /// </summary>
        [EnumMember(Value = "88")]
        NUMBER_88 = 89,

        /// <summary>
        /// Enum NUMBER_89 for value: 89
        /// </summary>
        [EnumMember(Value = "89")]
        NUMBER_89 = 90,

        /// <summary>
        /// Enum NUMBER_90 for value: 90
        /// </summary>
        [EnumMember(Value = "90")]
        NUMBER_90 = 91,

        /// <summary>
        /// Enum NUMBER_91 for value: 91
        /// </summary>
        [EnumMember(Value = "91")]
        NUMBER_91 = 92,

        /// <summary>
        /// Enum NUMBER_92 for value: 92
        /// </summary>
        [EnumMember(Value = "92")]
        NUMBER_92 = 93,

        /// <summary>
        /// Enum NUMBER_93 for value: 93
        /// </summary>
        [EnumMember(Value = "93")]
        NUMBER_93 = 94,

        /// <summary>
        /// Enum NUMBER_94 for value: 94
        /// </summary>
        [EnumMember(Value = "94")]
        NUMBER_94 = 95,

        /// <summary>
        /// Enum NUMBER_95 for value: 95
        /// </summary>
        [EnumMember(Value = "95")]
        NUMBER_95 = 96,

        /// <summary>
        /// Enum NUMBER_96 for value: 96
        /// </summary>
        [EnumMember(Value = "96")]
        NUMBER_96 = 97,

        /// <summary>
        /// Enum NUMBER_97 for value: 97
        /// </summary>
        [EnumMember(Value = "97")]
        NUMBER_97 = 98,

        /// <summary>
        /// Enum NUMBER_98 for value: 98
        /// </summary>
        [EnumMember(Value = "98")]
        NUMBER_98 = 99,

        /// <summary>
        /// Enum NUMBER_99 for value: 99
        /// </summary>
        [EnumMember(Value = "99")]
        NUMBER_99 = 100,

        /// <summary>
        /// Enum NUMBER_100 for value: 100
        /// </summary>
        [EnumMember(Value = "100")]
        NUMBER_100 = 101,

        /// <summary>
        /// Enum NUMBER_101 for value: 101
        /// </summary>
        [EnumMember(Value = "101")]
        NUMBER_101 = 102,

        /// <summary>
        /// Enum NUMBER_102 for value: 102
        /// </summary>
        [EnumMember(Value = "102")]
        NUMBER_102 = 103,

        /// <summary>
        /// Enum NUMBER_103 for value: 103
        /// </summary>
        [EnumMember(Value = "103")]
        NUMBER_103 = 104,

        /// <summary>
        /// Enum NUMBER_104 for value: 104
        /// </summary>
        [EnumMember(Value = "104")]
        NUMBER_104 = 105,

        /// <summary>
        /// Enum NUMBER_105 for value: 105
        /// </summary>
        [EnumMember(Value = "105")]
        NUMBER_105 = 106,

        /// <summary>
        /// Enum NUMBER_106 for value: 106
        /// </summary>
        [EnumMember(Value = "106")]
        NUMBER_106 = 107,

        /// <summary>
        /// Enum NUMBER_107 for value: 107
        /// </summary>
        [EnumMember(Value = "107")]
        NUMBER_107 = 108,

        /// <summary>
        /// Enum NUMBER_108 for value: 108
        /// </summary>
        [EnumMember(Value = "108")]
        NUMBER_108 = 109,

        /// <summary>
        /// Enum NUMBER_109 for value: 109
        /// </summary>
        [EnumMember(Value = "109")]
        NUMBER_109 = 110,

        /// <summary>
        /// Enum NUMBER_110 for value: 110
        /// </summary>
        [EnumMember(Value = "110")]
        NUMBER_110 = 111,

        /// <summary>
        /// Enum NUMBER_111 for value: 111
        /// </summary>
        [EnumMember(Value = "111")]
        NUMBER_111 = 112,

        /// <summary>
        /// Enum NUMBER_112 for value: 112
        /// </summary>
        [EnumMember(Value = "112")]
        NUMBER_112 = 113,

        /// <summary>
        /// Enum NUMBER_113 for value: 113
        /// </summary>
        [EnumMember(Value = "113")]
        NUMBER_113 = 114,

        /// <summary>
        /// Enum NUMBER_114 for value: 114
        /// </summary>
        [EnumMember(Value = "114")]
        NUMBER_114 = 115,

        /// <summary>
        /// Enum NUMBER_115 for value: 115
        /// </summary>
        [EnumMember(Value = "115")]
        NUMBER_115 = 116,

        /// <summary>
        /// Enum NUMBER_116 for value: 116
        /// </summary>
        [EnumMember(Value = "116")]
        NUMBER_116 = 117,

        /// <summary>
        /// Enum NUMBER_117 for value: 117
        /// </summary>
        [EnumMember(Value = "117")]
        NUMBER_117 = 118,

        /// <summary>
        /// Enum NUMBER_118 for value: 118
        /// </summary>
        [EnumMember(Value = "118")]
        NUMBER_118 = 119,

        /// <summary>
        /// Enum NUMBER_119 for value: 119
        /// </summary>
        [EnumMember(Value = "119")]
        NUMBER_119 = 120,

        /// <summary>
        /// Enum NUMBER_120 for value: 120
        /// </summary>
        [EnumMember(Value = "120")]
        NUMBER_120 = 121,

        /// <summary>
        /// Enum NUMBER_121 for value: 121
        /// </summary>
        [EnumMember(Value = "121")]
        NUMBER_121 = 122,

        /// <summary>
        /// Enum NUMBER_122 for value: 122
        /// </summary>
        [EnumMember(Value = "122")]
        NUMBER_122 = 123,

        /// <summary>
        /// Enum NUMBER_123 for value: 123
        /// </summary>
        [EnumMember(Value = "123")]
        NUMBER_123 = 124,

        /// <summary>
        /// Enum NUMBER_124 for value: 124
        /// </summary>
        [EnumMember(Value = "124")]
        NUMBER_124 = 125,

        /// <summary>
        /// Enum NUMBER_125 for value: 125
        /// </summary>
        [EnumMember(Value = "125")]
        NUMBER_125 = 126,

        /// <summary>
        /// Enum NUMBER_126 for value: 126
        /// </summary>
        [EnumMember(Value = "126")]
        NUMBER_126 = 127,

        /// <summary>
        /// Enum NUMBER_127 for value: 127
        /// </summary>
        [EnumMember(Value = "127")]
        NUMBER_127 = 128,

        /// <summary>
        /// Enum NUMBER_128 for value: 128
        /// </summary>
        [EnumMember(Value = "128")]
        NUMBER_128 = 129,

        /// <summary>
        /// Enum NUMBER_129 for value: 129
        /// </summary>
        [EnumMember(Value = "129")]
        NUMBER_129 = 130,

        /// <summary>
        /// Enum NUMBER_130 for value: 130
        /// </summary>
        [EnumMember(Value = "130")]
        NUMBER_130 = 131,

        /// <summary>
        /// Enum NUMBER_131 for value: 131
        /// </summary>
        [EnumMember(Value = "131")]
        NUMBER_131 = 132,

        /// <summary>
        /// Enum NUMBER_132 for value: 132
        /// </summary>
        [EnumMember(Value = "132")]
        NUMBER_132 = 133,

        /// <summary>
        /// Enum NUMBER_133 for value: 133
        /// </summary>
        [EnumMember(Value = "133")]
        NUMBER_133 = 134,

        /// <summary>
        /// Enum NUMBER_134 for value: 134
        /// </summary>
        [EnumMember(Value = "134")]
        NUMBER_134 = 135,

        /// <summary>
        /// Enum NUMBER_135 for value: 135
        /// </summary>
        [EnumMember(Value = "135")]
        NUMBER_135 = 136,

        /// <summary>
        /// Enum NUMBER_136 for value: 136
        /// </summary>
        [EnumMember(Value = "136")]
        NUMBER_136 = 137,

        /// <summary>
        /// Enum NUMBER_137 for value: 137
        /// </summary>
        [EnumMember(Value = "137")]
        NUMBER_137 = 138,

        /// <summary>
        /// Enum NUMBER_138 for value: 138
        /// </summary>
        [EnumMember(Value = "138")]
        NUMBER_138 = 139,

        /// <summary>
        /// Enum NUMBER_139 for value: 139
        /// </summary>
        [EnumMember(Value = "139")]
        NUMBER_139 = 140,

        /// <summary>
        /// Enum NUMBER_140 for value: 140
        /// </summary>
        [EnumMember(Value = "140")]
        NUMBER_140 = 141,

        /// <summary>
        /// Enum NUMBER_141 for value: 141
        /// </summary>
        [EnumMember(Value = "141")]
        NUMBER_141 = 142,

        /// <summary>
        /// Enum NUMBER_142 for value: 142
        /// </summary>
        [EnumMember(Value = "142")]
        NUMBER_142 = 143,

        /// <summary>
        /// Enum NUMBER_143 for value: 143
        /// </summary>
        [EnumMember(Value = "143")]
        NUMBER_143 = 144,

        /// <summary>
        /// Enum NUMBER_144 for value: 144
        /// </summary>
        [EnumMember(Value = "144")]
        NUMBER_144 = 145,

        /// <summary>
        /// Enum NUMBER_145 for value: 145
        /// </summary>
        [EnumMember(Value = "145")]
        NUMBER_145 = 146,

        /// <summary>
        /// Enum NUMBER_146 for value: 146
        /// </summary>
        [EnumMember(Value = "146")]
        NUMBER_146 = 147,

        /// <summary>
        /// Enum NUMBER_147 for value: 147
        /// </summary>
        [EnumMember(Value = "147")]
        NUMBER_147 = 148,

        /// <summary>
        /// Enum NUMBER_148 for value: 148
        /// </summary>
        [EnumMember(Value = "148")]
        NUMBER_148 = 149,

        /// <summary>
        /// Enum NUMBER_149 for value: 149
        /// </summary>
        [EnumMember(Value = "149")]
        NUMBER_149 = 150,

        /// <summary>
        /// Enum NUMBER_150 for value: 150
        /// </summary>
        [EnumMember(Value = "150")]
        NUMBER_150 = 151,

        /// <summary>
        /// Enum NUMBER_151 for value: 151
        /// </summary>
        [EnumMember(Value = "151")]
        NUMBER_151 = 152,

        /// <summary>
        /// Enum NUMBER_152 for value: 152
        /// </summary>
        [EnumMember(Value = "152")]
        NUMBER_152 = 153,

        /// <summary>
        /// Enum NUMBER_153 for value: 153
        /// </summary>
        [EnumMember(Value = "153")]
        NUMBER_153 = 154,

        /// <summary>
        /// Enum NUMBER_154 for value: 154
        /// </summary>
        [EnumMember(Value = "154")]
        NUMBER_154 = 155,

        /// <summary>
        /// Enum NUMBER_155 for value: 155
        /// </summary>
        [EnumMember(Value = "155")]
        NUMBER_155 = 156,

        /// <summary>
        /// Enum NUMBER_156 for value: 156
        /// </summary>
        [EnumMember(Value = "156")]
        NUMBER_156 = 157,

        /// <summary>
        /// Enum NUMBER_157 for value: 157
        /// </summary>
        [EnumMember(Value = "157")]
        NUMBER_157 = 158,

        /// <summary>
        /// Enum NUMBER_158 for value: 158
        /// </summary>
        [EnumMember(Value = "158")]
        NUMBER_158 = 159,

        /// <summary>
        /// Enum NUMBER_159 for value: 159
        /// </summary>
        [EnumMember(Value = "159")]
        NUMBER_159 = 160,

        /// <summary>
        /// Enum NUMBER_160 for value: 160
        /// </summary>
        [EnumMember(Value = "160")]
        NUMBER_160 = 161,

        /// <summary>
        /// Enum NUMBER_161 for value: 161
        /// </summary>
        [EnumMember(Value = "161")]
        NUMBER_161 = 162,

        /// <summary>
        /// Enum NUMBER_162 for value: 162
        /// </summary>
        [EnumMember(Value = "162")]
        NUMBER_162 = 163,

        /// <summary>
        /// Enum NUMBER_163 for value: 163
        /// </summary>
        [EnumMember(Value = "163")]
        NUMBER_163 = 164,

        /// <summary>
        /// Enum NUMBER_164 for value: 164
        /// </summary>
        [EnumMember(Value = "164")]
        NUMBER_164 = 165,

        /// <summary>
        /// Enum NUMBER_165 for value: 165
        /// </summary>
        [EnumMember(Value = "165")]
        NUMBER_165 = 166

    }

}
