/*
 * 3E API
 *
 * The 3E Public API provides a powerful and convenient Web Services API for interacting with the 3E platform. The 3E API endpoints are a common integration point to allow programmatic interaction with the 3E business logic and data.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// NextGenFrameworkManagersDMSMgrIDMSFolder
    /// </summary>
    [DataContract]
    public partial class NextGenFrameworkManagersDMSMgrIDMSFolder :  IEquatable<NextGenFrameworkManagersDMSMgrIDMSFolder>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NextGenFrameworkManagersDMSMgrIDMSFolder" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public NextGenFrameworkManagersDMSMgrIDMSFolder()
        {
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=true)]
        public string Id { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=true)]
        public string Name { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public NextGenFrameworkManagersDMSMgrImObjectType Type { get; private set; }

        /// <summary>
        /// Gets or Sets IsHidden
        /// </summary>
        [DataMember(Name="isHidden", EmitDefaultValue=false)]
        public bool IsHidden { get; private set; }

        /// <summary>
        /// Gets or Sets DocCount
        /// </summary>
        [DataMember(Name="docCount", EmitDefaultValue=false)]
        public int DocCount { get; private set; }

        /// <summary>
        /// Gets or Sets SubFolders
        /// </summary>
        [DataMember(Name="subFolders", EmitDefaultValue=true)]
        public List<NextGenFrameworkManagersDMSMgrIDMSFolder> SubFolders { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NextGenFrameworkManagersDMSMgrIDMSFolder {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  IsHidden: ").Append(IsHidden).Append("\n");
            sb.Append("  DocCount: ").Append(DocCount).Append("\n");
            sb.Append("  SubFolders: ").Append(SubFolders).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NextGenFrameworkManagersDMSMgrIDMSFolder);
        }

        /// <summary>
        /// Returns true if NextGenFrameworkManagersDMSMgrIDMSFolder instances are equal
        /// </summary>
        /// <param name="input">Instance of NextGenFrameworkManagersDMSMgrIDMSFolder to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NextGenFrameworkManagersDMSMgrIDMSFolder input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.IsHidden == input.IsHidden ||
                    (this.IsHidden != null &&
                    this.IsHidden.Equals(input.IsHidden))
                ) && 
                (
                    this.DocCount == input.DocCount ||
                    (this.DocCount != null &&
                    this.DocCount.Equals(input.DocCount))
                ) && 
                (
                    this.SubFolders == input.SubFolders ||
                    this.SubFolders != null &&
                    input.SubFolders != null &&
                    this.SubFolders.SequenceEqual(input.SubFolders)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.IsHidden != null)
                    hashCode = hashCode * 59 + this.IsHidden.GetHashCode();
                if (this.DocCount != null)
                    hashCode = hashCode * 59 + this.DocCount.GetHashCode();
                if (this.SubFolders != null)
                    hashCode = hashCode * 59 + this.SubFolders.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
